game/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from spin.views import keno_update_view, spin_update_view

urlpatterns = [
    path('', include('cashierapp.urls')),
    path('api/', include('keno.api.urls')),
    path('spin/', include('spin.api.urls')),
    # path('users/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('zuser/', include('zuser.urls')),
    path('mobile/', include('mobile.urls')),
    path('admin/', admin.site.urls),
    path('keno-update-view/', keno_update_view, name='kuv'),
    path('spin-update-view/', spin_update_view, name='suv'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         path('debug/', include(debug_toolbar.urls)),
#     ]

# if not settings.DEBUG:
#     urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

keno/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import KenoResultViewSet, KenoMainGameView

router = DefaultRouter()
router.register(r'keno', KenoResultViewSet, basename='keno')


urlpatterns = [
    path('', KenoMainGameView.as_view(), name='keno-main-game'),
]

urlpatterns += router.urls

mobile/urls.py
from django.urls import path
from .views import (MobilePlayers, get_result, main_page, mobile_keno, get_live_bets, get_results,
mobile_bingo, bingo_card_results, get_bingo_cards, mobile_spin, mobile_dice)
app_name = 'mobile'

urlpatterns = [
    path('', main_page, name='keno'),
    path('index/', MobilePlayers.as_view(), name='index'),
    path('latest/', get_result, name='get_latest_result'),
    path('keno-req/', mobile_keno, name='keno_req'),
    path('get-live-bets/', get_live_bets, name='get_live_bets'),
    path('keno-results/', get_results, name='keno_results'),
    path('bingo/', mobile_bingo, name='bingo'),
    path('bingo-results/', bingo_card_results, name='bingo_results'),
    path('bingo-cards/', get_bingo_cards, name='get-bingo-cards'),
    path('spin/', mobile_spin, name='spin'),
    path('dice/', mobile_dice, name='dice'),
]

spin/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import SpinMainGameView, SpinResultViewSet

router = DefaultRouter()
router.register(r'api', SpinResultViewSet, basename='spin')


urlpatterns = [
    path('', SpinMainGameView.as_view(), name='spin-main-game'),
]

urlpatterns += router.urls

keno/api/models.py
from django.db import models

# Create your models here.

mobile/models.py
from django.db import models

# Create your models here.

keno/api/views.py
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import render

from rest_framework.decorators import action
from rest_framework import viewsets
from keno.models import Game, GameResult
from zuser.models import Agent
from .serializers import GameNumberSerializer, GameOpenSerializer

from django.views.generic import TemplateView

import os
import json
from django.conf import settings

def json_file_view(request):
    file_path = os.path.join(settings.BASE_DIR, 'apigame', 'spin-open.json')
    with open(file_path, 'r') as json_file:
        data = json.load(json_file)
    return JsonResponse(data)

class KenoMainGameView(TemplateView):
    def get(self, request):
        username = get_agent(request)
        if username == None:
            return HttpResponse('Username is not FoundNot Allowed')
        return render(request, 'keno/great.html')

class KenoResultViewSet(viewsets.ModelViewSet):
    queryset = GameResult.objects.all()
    serializer_class = GameOpenSerializer

    def get_serializer_class(self):
        if self.action == 'number':
            return GameNumberSerializer
        elif self.action == 'open':
            return GameOpenSerializer
        else:
            return super().get_serializer_class()

    @staticmethod
    def get_open_game():
        return Game.objects.filter(status='OPEN').order_by('-created_at').first()

    @staticmethod
    def get_game_number(request):
        game_number = request.GET.get('gameNumber')
        return game_number

    @action(detail=False, methods=['get'])
    def number(self, request):
        agent = get_agent(request)
        if agent == None:
            return JsonResponse(status=404, data={'get_result':"not allowed"})
        game_number = self.get_game_number(request)
        if game_number:
            pass
        queryset = Game.objects.all()
        serializer_class = self.get_serializer_class()
        serializer = serializer_class(queryset, context={'agent': agent})
        return JsonResponse(serializer.data, safe=False)

    @action(detail=False, methods=['get'])
    def open(self, request):
        agent = get_agent(request)
        if agent == None:
            return JsonResponse(status=404, data={'get_result':"not allowed"})
        else:
            queryset = Game.objects.all()
            serializer_class = self.get_serializer_class()
            serializer = serializer_class(queryset, context={'agent': agent})
            return JsonResponse(serializer.data, safe=False)

def get_agent(request):
    username = request.session.get('username')

    # If username isn't found in session, try to get it from request.GET
    if not username:
        username = request.GET.get('username')
    if username:
        # Try to fetch the agent based on the username
        try:
            agent = Agent.objects.get_agent_by_username(username)
            # Store the username in the session for future requests
            request.session['username'] = username
            return agent
        except Agent.DoesNotExist:
            # If agent is not found, raise a 404 error
            raise Http404("Agent not found")

    # If no username is found, return None
    return None

mobile/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View

from datetime import datetime
import json
from django.http import JsonResponse
from django.shortcuts import render

from django.views import View
from game_utils.auth_decorators import user_type_redirect
from game_utils.time_file import get_local_time_date, get_local_time_now, single_date
from game_utils.et_names import names

from keno.utils.mobile_ticket import MobileSaveSelection
import logging

logger = logging.getLogger(__name__)
from django.shortcuts import redirect
from django.shortcuts import render
from django.views import View
import time
from datetime import datetime, timedelta
from keno.models import MobileGame, MobileTicket
import json
from django.utils import timezone
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from zuser.models import Player
from django.db.models import Sum, Q
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

import random

def mobile_dice(request):
    return render(request, 'mobile/dice.html', context={'game_type': 'dice'})

def mobile_spin(request):
    return render(request, 'mobile/spin.html', context={'game_type': 'spin'})

def mobile_bingo(request):
    return render(request, 'mobile/bingo.html', context={'game_type': 'bingo'})

def generate_nums():
  B = random.sample(range(1, 15), 5)
  I = random.sample(range(16, 31), 5)
  N = random.sample(range(31, 45), 5)
  G = random.sample(range(46, 60), 5)
  O = random.sample(range(61, 75), 5)
  return [B,I,N,G,O]


def bingo_card_results(request):
    card = []
    for _ in range(3):
        card.append(generate_nums())
    print(card)
    return JsonResponse(card, safe=False)

def get_bingo_cards(request):
    card = []
    for _ in range(5):
        card.append(generate_nums())
    print(card)
    return JsonResponse(card, safe=False)

def get_results(request):
    # Generate 20 unique random numbers between 1 and 80
    random_numbers = random.sample(range(1, 81), 20)
    return JsonResponse(random_numbers, safe=False)

def mask_name(name):
    if len(name) <= 2:
        return '*' * len(name)
    else:
        return name[:-2] + '***'

def get_live_bets(request):
    chat_messages = []
    for _ in range(10):
        sender_name = random.choice(list(names.keys()))
        message_length = random.randint(1, 10)
        message = ', '.join(str(random.randint(1, 80)) for _ in range(message_length))
        time = random.randint(1, 12) * 10  # Time (stake) between 100 and 200

        masked_name = mask_name(sender_name)
        chat_messages.append({
            'senderName': masked_name,
            'message': message,
            'time': time
        })

    return JsonResponse(chat_messages, safe=False)

def place_bet(json_data, player):
    latest_game = MobileGame.objects.latest_keno_open()
    if not latest_game:
        return JsonResponse({'status': 'error', 'message': 'please wait a moment, game is not created'})
    else:
        current_time = get_local_time_now()
        latest_game_created_at = timezone.localtime(latest_game.created_at)
        time_difference = current_time - latest_game_created_at

        if not time_difference.total_seconds() < 235:
            time.sleep(5)
            return JsonResponse({'status': 'error', 'message': 'time is up'})
        else:
            input_type = json_data.get('input_type')
            _selection = MobileSaveSelection()
            message = 'saved successfully'
            print(message)
            if input_type == "single":
                r = _selection.add_single_ticket(json_data, player)
            elif input_type == "multiple":
                r = _selection.add_multiple_tickets(json_data, player)
            
            return JsonResponse({'message': message, 'status': 'success', 'data': r}, status=200)

def balance_report(request):
    player = Player.objects.get(player=request.user)
    data = {}
    json_data = json.loads(request.body)
    requested_date_str = json_data.get('date')
    if requested_date_str:
        data = get_ticket_data_by_date(player, requested_date_str)
    else:
        data = get_ticket_data(player)
    return JsonResponse(data)

@csrf_exempt
@login_required
def mobile_keno(request):
    if request.method == 'POST':
        content_type = request.headers.get('Content-Type')
        custom_user = request.user
        player = get_object_or_404(Player, player=custom_user)
        if 'application/json' in content_type:
            json_data = json.loads(request.body)
            action = json_data.get('action')
            if action == 'place_bet':
                return place_bet(json_data, player)
            elif action == 'get_result':
                return get_result(request, json_data)
            elif action == 'balance_report':
                return balance_report(request)
            elif action == 'ticket_history':
                response_data = MobileTicket.objects.last_100_selections(player)
                # print(response_data)
                return JsonResponse(response_data, safe=False, status=200)
            else:
                result = {'status': 'error', 'message': 'Invalid action'}
                return JsonResponse(result, status=400)
        else:
            result = {'status': 'error', 'message': 'Unsupported content type'}
            return JsonResponse(result, status=400)

    # If the request method is not POST
    return JsonResponse({'message': 'Only POST requests are allowed', 'status': 'error'}, status=405)

@user_type_redirect
def main_page(request):
    custom_user = request.user
    try:
        player = get_object_or_404(Player, player=custom_user)
    except ObjectDoesNotExist:
        return redirect('/dashboard')
    return render(request, 'mobile/keno.html', {'game_type' : 'keno', 'player': player, 'custom_user':custom_user})

def get_result(request):
    start_time = time.time()
    while True:
        latest_game = MobileGame.objects.latest_keno_result()
        try:
            result = latest_game.result
        except:
            print(f'no result for mobile')
        if result:
            response_data = MobileTicket.objects.get_response_data(latest_game, request)
            return JsonResponse(response_data)
        if time.time() - start_time > 4 * 60:
            response_data = {'latest_result': 'No new result is made'}
            return JsonResponse(response_data)
        time.sleep(5)


def latest_game_num(request):
    start_time = time.time()
    while True:
        latest_game = MobileGame.objects.latest_keno()
        if latest_game:
            creation_time = latest_game.created_at.strftime('%Y-%m-%d %H:%M:%S')
            creation_time = datetime.strptime(creation_time, '%Y-%m-%d %H:%M:%S')

            creation_time_plus_one_sec = creation_time + timedelta(seconds=1)
            creation_time = creation_time_plus_one_sec.strftime('%Y-%m-%d %H:%M:%S')
            response_data = {
                'latest_game': latest_game.game_num,
                'creation_time': creation_time
            }
            return JsonResponse(response_data)
        if time.time() - start_time > 4 * 60:
            response_data = {'latest_game': 'No new game made'}
            return JsonResponse(response_data)
        time.sleep(5)


class MobilePlayers(View):
    redirect_authenticated_user = True  # Redirect authenticated user if they try to access the login page

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.context = {'status': 200}
        self.model = MobileGame
        self.common_context = {'app_name': 'BettingApp'}
        self.template_name = 'mobile/keno.html'
        self.enable_feature_x = True
        self.default_filter = {'status': 'active'}
        self.keno_odd_beta = [
            [1, 4],
            [2, 15],
            [3, 35],
            [4, 100],
            [5, 300],
            [6, 1800],
            [7, 2150],
            [8, 3000],
            [9, 4200],
            [10, 5000]
        ]
        self.numbers_list = list(range(1, 81))

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if user.groups.filter(name='Cashier').exists():
            return redirect('/cashier/')
        elif user.groups.filter(name='Agent Admin').exists():
            return redirect('/dashboard/')
        elif user.groups.filter(name='Company Admin').exists() or request.user.is_staff:
            return redirect('/dashboard/')
        else:
            pass

        request_type = request.GET.get('type')

        if request_type == 'printBalance':
            day = request.GET.get('day')
            data = {
                "agent": "Agent Name",
                "cashier": "Cashier Name",
                "date": "2024-03-18",
                "betCount": 100,
                "payin": 5000,
                "payout": 3000,
                "canceled": 200,
                "net": 1800
            }
            return JsonResponse(data)
        elif request_type == 'ticket_history':
            ticket_history_data = [
                {
                    'code': '123456',
                    'id': 1,
                    'on': '2024-03-19',
                    'stake': 100
                },
                {
                    'code': '789012',
                    'id': 2,
                    'on': '2024-03-18',
                    'stake': 200
                }
            ]
            response_data = ticket_history_data
            return JsonResponse(response_data, safe=False)
        today = get_local_time_date()
        game_instance = self.model.objects.latest_keno()
        if game_instance:
            game_num = game_instance.game_num
            self.context = {
                'numbers_list': self.numbers_list,
                'keno_odd': self.keno_odd_beta,
                'game_num': game_num,

spin/views.py
# Inside views.py of your Django app (e.g., betapp)
from django.http import HttpResponse
from keno.tasks import keno_update_tasks
from spin.tasks import update_spin_game
from datetime import datetime

def keno_update_view(request):
    keno_update_tasks()  # Call your keno update task
    print(f"Keno update executed at: {datetime.now()}")
    return HttpResponse(f"Keno update executed at: {datetime.now()}")

def spin_update_view(request):
    update_spin_game()  # Call your spin update task
    return HttpResponse(f"Spin game update executed at: {datetime.now()}")

mobile/templates/mobile/_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

  <title>Maya Bets</title>
  <!-- Bootstrap CSS -->
  <link rel="icon" type="image/x-icon" href="{% static 'img/mayabets_logo.ico' %}">

  <link rel="stylesheet" href="{% static 'mobile/live_chats.css' %}">
  <link rel="stylesheet" href="{% static 'mobile/bootstrap.min.css' %}">
  <!-- Font Awesome CSS -->
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"> -->
  <script src="{% static 'mobile/jquery.min.js' %}"></script>
  <!-- Bootstrap JS -->
  <script src="{% static 'mobile/popper.min.js' %}"></script>
  <script src="{% static 'mobile/bootstrap.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://kit.fontawesome.com/f7b6734354.js" crossorigin="anonymous"></script>
  <style>
/* Sticky header */
::-moz-selection { /* Code for Firefox */
background-color: transparent;
}

::selection {
  background-color: transparent;
}
    body {
      background-color: #00203FFF;
      font-family: Arial, sans-serif;
    }

    .sticky-header {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      background-color: #00203FFF;
      color: #fff;
      padding: 0;
      text-align: center;
      z-index: 1000;
      box-shadow: 0px 3px 10px rgba(0, 0, 0, 0.6);
      /* Add elevation */
    }

    /* Sticky footer */
    .sticky-footer {
      position: fixed;
      bottom: 0;
      left: 0;
      width: 100%;
      background-color: #00203FFF;
      color: #fff;
      padding: 1px 0;
      margin: 0;
      text-align: center;
      box-shadow: 0px 3px 10px rgba(0, 0, 0, 0.2);
      /* Add elevation */
    }

    .main-content {
      padding-bottom: 60px;
      max-height: calc(100vh - 90px) !important;
      background-color: #00203FFF;
    }

    .navbar-brand {
      font-weight: bold;
    }

    #notification-container {
    position: fixed;
    top: 10px;
    right: 20px;
    z-index: 1050;
    /* Adjust as needed */
  }

  #notification {
    display: none;
    animation: slideIn 0.2s ease-in-out forwards;
  }

  /* Center the timer text */
  .navbar-nav {
    flex-grow: 1;
    justify-content: center;
  }

    * {
      margin: 0;
      padding: 0
    }

    /* start profile styles */
    .card {
      width: 350px;
      background-color: #efefef;
      border: none;
      cursor: pointer;
      transition: all 0.5s;
    }

    .image img {
      transition: all 0.5s
    }

    .card:hover .image img {
      transform: scale(1.5)
    }

    .name {
      font-size: 22px;
      font-weight: bold
    }

    .idd {
      font-size: 14px;
      font-weight: 600
    }

    .idd1 {
      font-size: 12px
    }

    .number {
      font-size: 22px;
      font-weight: bold
    }

    .follow {
      font-size: 12px;
      font-weight: 500;
      color: #444444
    }

    .btn1 {
      height: 40px;
      width: 150px;
      border: none;
      background-color: #000;
      color: #aeaeae;
      font-size: 15px
    }

    .icons i {
      font-size: 19px
    }

    hr .new1 {
      border: 1px solid
    }

    .join {
      font-size: 14px;
      color: #a0a0a0;
      font-weight: bold
    }

    .date {
      background-color: #ccc
    }

/* end */
  </style>
  {% block style %}
  {% endblock %}
</head>

<body>

{% include 'mobile/nav.html' with active_tab=game_type %}

{% include 'mobile/timer-game-num.html' %}
<main class="container-fluid main-content">
{% block content %}
{% endblock %}
</main>

{% block footer %}
{% endblock %}

{% include 'mobile/info-modal.html' %}

{% block script %}
{% endblock %}

<script>
  
  document.addEventListener('DOMContentLoaded', function () {
      // Function to add a new chat message to the top of the chat view
      function addNewChatMessage(chatItem) {
        const chatView = document.getElementById('chatView');
        chatView.insertBefore(chatItem, chatView.firstChild);
        // Scroll to the top of the chat view after adding the new message
        chatView.scrollTop = 0;
      }

      // Function to create a new chat message element
      function createChatItem(senderName, message, time) {
        const chatItem = document.createElement('div');
        chatItem.classList.add('chat-item');

        const innerHtml = `
            <div class="d-flex">
                <img class"img" src="{% static 'mobile/img/player-gamer.avif' %}" alt="PI">
                <div class="p-1">
                    <div class="d-flex align-items-end">
                        <div class="small sender-name"><a href="#">${senderName}</a></div>
                        <div class="small chat-time">${time}</div>
                    </div>
                    <div class="small chat-text">
                        ${message}
                    </div>
                </div>
            </div>
        `;
        chatItem.innerHTML = innerHtml;

        return chatItem;
      }

      function getLiveBets() {
        $.ajax({
          url: "{% url 'mobile:get_live_bets' %}",
          type: 'GET',
          success: function (response) {
            response.forEach((message, index) => {
              setTimeout(() => {
                const chatItem = createChatItem(message.senderName, message.message, message.time);
                addNewChatMessage(chatItem);
              }, index * 250);
            });
          },
          error: function (xhr, status, error) {
            // Handle errors
            console.error(error);
          }
        });
      }

      // Call getLiveBets initially and then at intervals
      getLiveBets(); // Call initially
      // setInterval(getLiveBets, 10000); // Call every minute (adjust as needed)
    });

    $(document).ready(function () {
      var intervalTimer; // Variable to hold the interval timer

      function updateTimer() {
        var now = new Date();
        var minutes = Math.floor((now.getTime() / 1000) / 60); // Calculate minutes
        var seconds = 59 - now.getSeconds(); // Calculate remaining seconds
        var timerText = '00' + ':' + pad(seconds);
        $('#timer').text(timerText);

        // If timer reaches 00:00, trigger closed state
        if (seconds === 0 || seconds >= 55) {
          handleClosedState();
        }
      }

      function pad(num) {
        return (num < 10 ? '0' : '') + num;
      }

      // Initial update and start the interval timer
      updateTimer();
      intervalTimer = setInterval(updateTimer, 1000);

      // Change timer text to "Closed" for 5 seconds when it reaches 00:00
      function handleClosedState() {
        $('#timer').text('Closed');
        clearInterval(intervalTimer); // Stop the interval timer
        setTimeout(function () {
          updateTimer(); // Update the timer after 5 seconds
          intervalTimer = setInterval(updateTimer, 1000); // Restart the interval timer
        }, 5000);
      }
    });

</script>
</body>

</html>

mobile/templates/mobile/chat.html
<div class="col-12 m-0 p-0">
    <section class="main-wrapper">
        <div class="cgl-live-chat">
            <div class="chat-wrapper">
                <!-- <div class="chat-title">
                Live Bet
            </div> -->
                <div class="chat-view" id="chatView">
                </div>
            </div>
        </div>
    </section>
</div>

mobile/templates/mobile/dice.html
<!DOCTYPE html>
<!-- Coding by royal 420 KE | youtube.com/royal420ke -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Roll dice project | Royal 420 KE</title>
<style>
    *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: sans-serif;
    border: 0;
    outline: 0;
}
body{
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    background: rgba(221,50,125);
}
.container{
    display: grid;
    place-items: center;
    width: 250px;
    background: #eee;
    padding: 60px 0 40px;
    border-radius: 30px;
    box-shadow: rgba(0,0,0,0.1);
}
.dice{
    position: relative;
    width: 100px;
    height: 100px;
    transform-style: preserve-3d;
    transition: 1s ease;
    
}
@keyframes rolling{
    50%{
        transform: rotateX(455deg) rotateY(455deg);
    }
}
.face{
    position: absolute;
    width: 100%;
    height: 100%;
    border: 5px solid #f6f3f0;
    border-radius: 20px;
    background: linear-gradient(145deg, 
    #dddbd8,#fff);
    transform-style: preserve-3d;
}
.face::before{
    content: '';
    position: absolute;
    width: 100%;
    height: 100%;
    border-radius: 20px;
    background: #f6f3f0;
    transform: translateZ(-1px);
}
.face::after{
    content: '';
    position: absolute;
    left: 50%;
    top: 50%;
    width: 18px;
    height: 18px;
    background: #000;
    border-radius: 50%;
}
.front{
    transform: translateZ(50px);
}
.back{
    transform: rotateX(180deg) translateZ(50px);
}
.top{
    transform: rotateX(90deg) translateZ(50px);
}
.bottom{
    transform: rotateX(-90deg) translateZ(50px);
}
.right{
    transform: rotateY(90deg) translateZ(50px);
}
.left{
    transform: rotateY(-90deg) translateZ(50px);
}
.front::after{
    width: 30px;
    height: 30px;
    background: #000;
    margin: -15px 0 0 -15px;
}
.back::after{
    margin: -35px 0 0 -30px;
    box-shadow: 40px 0,
    0 25px,
    40px 25px,
    0 50px,
    40px 50px;
}
.top::after{
    margin: -30px 0 0 -30px;
    box-shadow: 40px 40px;
}
.bottom::after{
    margin: -36px 0 0 -36px;
    box-shadow: 26px 26px,
    52px 52px,
    52px 0,
    0 52px;
}
.right::after{
    margin: -30px 0 0 -30px;
    box-shadow: 40px 0,
    0 40px,
    40px 40px;
}
.left::after{
    margin: -35px 0 0 -35px;
    box-shadow: 25px 25px,
    50px 50px;
}
.roll{
    color: rgba(221,50,125);
    margin-top: 60px;
    padding: 6px 12px;
    border-radius: 3px;
    font-size: 16px;
    font-weight: 600;
    border: 2px solid rgba(221,50,125);
    cursor: pointer;
}
.roll:hover{
    color: #fff;
    background: rgba(221,50,125);
}
</style>
</head>
<body>
    <div class="container">
        <div class="dice">
            <div class="face front"></div>
            <div class="face back"></div>
            <div class="face top"></div>
            <div class="face bottom"></div>
            <div class="face right"></div>
            <div class="face left"></div>
        </div>
        <button class="roll">
            <h2>Roll Dice</h2>
        </button>
    </div>
    <script>
        const dice = document.querySelector('.dice');
        const rollBtn = document.querySelector('.roll');


        const randomDice = () =>{
            const random = Math.floor(Math.random() * 10);
            if(random >= 1 && random <= 6){
                rollDice(random);
            }else{
                randomDice();
            }
        }

        const rollDice = random =>{
            dice.style.animation = 'rolling 4s';
            setTimeout(() =>{
                switch (random) {
                    case 1: dice.style.transform = 
                    'rotateX(0deg) rotateY(0deg)';
                    break;
                    case 6: dice.style.transform = 
                    'rotateX(180deg) rotateY(0deg)';
                    break;
                    case 2: dice.style.transform = 
                    'rotateX(-90deg) rotateY(0deg)';
                    break;
                    case 5: dice.style.transform = 
                    'rotateX(90deg) rotateY(0deg)';
                    break;
                    case 3: dice.style.transform = 
                    'rotateX(0deg) rotateY(90deg)';
                    break;
                    case 4: dice.style.transform = 
                    'rotateX(0deg) rotateY(-90deg)';
                    break;

                    default: break;
                }
                dice.style.animation = 'none';


            },4050);
        }
        

        rollBtn.addEventListener('click', randomDice);
    </script>
</body>
</html>

mobile/templates/mobile/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Keno: Simple</title>
  <script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'mobile/styles.css' %}" rel="stylesheet">
  <link href="{% static 'mobile/bs.css' %}" rel="stylesheet">

</head>
<body class="tinted-image">
{% block content %}
{% endblock %}
</body>
<script src="{% static 'mobile/bs.js' %}"></script>
<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
</html>

mobile/templates/mobile/nav.html
{% load static %}
<header class="sticky-header">
    <nav class="navbar navbar-expand navbar-dark pt-0 pb-0">
        <a class="navbar-brand p-0 mr-4" href="#">
            <img src="{% static 'img/mayabets_logo.jpg' %}" class="img rounded-circle" alt="Logo" width="30"
                height="30">
        </a>

          <ul class="navbar-nav mr-auto small">
            <li class="nav-item {% if active_tab == 'keno' %}active{% endif %}">
                <a class="nav-link" href="{% url 'mobile:keno' %}">
                    <i class="bi bi-layers"></i> Keno
                </a>
            </li>
            <li class="nav-item {% if active_tab == 'bingo' %}active{% endif %}">
                <a class="nav-link" href="{% url 'mobile:bingo' %}">
                    <i class="bi bi-grid"></i> Bingo
                </a>
            </li>
            <li class="nav-item {% if active_tab == 'spin' %}active{% endif %}">
                <a class="nav-link" href="{% url 'mobile:spin' %}">
                    <i class="bi bi-arrow-repeat"></i> Spin
                </a>
            </li>
            <li class="nav-item {% if active_tab == 'aviator' %}active{% endif %}">
                <a class="nav-link" href="#">
                    <i class="bi bi-airplane"></i> Aviator
                </a>
            </li>
            <li class="nav-item {% if active_tab == 'dice' %}active{% endif %}">
                <a class="nav-link" href="{% url 'mobile:dice' %}">
                    <i class="bi bi-dice"></i> Dice
                </a>
            </li>
          </ul>
          
      </nav>
</header>