dashboard/urls.py
from django.urls import path
from .views import (DashboardView, tickets_view, tickets_statistics_view, game_results_view, game_result_stats_view, shop_reports,
                    ManageCompanies, ManageUserPermissionsView,
                    ManageAgents, ManageCashiers, agents_statistics_view)

app_name = 'dashboard'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard_view'),
    path('manage-company/', ManageCompanies.as_view(), name='manage_company'),
    path('manage-agent/', ManageAgents.as_view(), name='manage_agent'),
    path('manage-cashier/', ManageCashiers.as_view(), name='manage_cashier'),
    path('manage-permission-group/<int:user_id>/', ManageUserPermissionsView.as_view(), name='manage_permission_group'),
    path('tickets/', tickets_view, name='tickets'),
    path('tickets-statistics/', tickets_statistics_view, name='tickets_statistics'),
    path('game-results/', game_results_view, name='game_results'),
    path('game-stats/', game_result_stats_view, name='game_results_stats'),
    path('shop-reports/', shop_reports, name='shop_agent_reports'),
    path('api-statistics/', agents_statistics_view, name='api_statistics'),
]

game/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from spin.views import keno_update_view, spin_update_view

urlpatterns = [
    path('', include('cashierapp.urls')),
    path('api/', include('keno.api.urls')),
    path('spin/', include('spin.api.urls')),
    # path('users/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('zuser/', include('zuser.urls')),
    path('mobile/', include('mobile.urls')),
    path('admin/', admin.site.urls),
    path('keno-update-view/', keno_update_view, name='kuv'),
    path('spin-update-view/', spin_update_view, name='suv'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         path('debug/', include(debug_toolbar.urls)),
#     ]

# if not settings.DEBUG:
#     urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

zuser/urls.py
from django.urls import path, include
# from allauth.account.views import LoginView

from .views import (
	company_list, lock_agent,
	company_detail, 
	company_create, 
	company_update, 
	company_delete, agent_detail, cashier_create, cashier_detail, login_view,
    signup_view, forgot_password_view,create_superuser_view, logout_view, change_password)
app_name = 'zuser'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', signup_view, name='signup'),
    path('forgot-password/', forgot_password_view, name='forgot_password'),
    path('create-superuser/', create_superuser_view, name='create_superuser'),
    path('logout/', logout_view, name='logout'),
    # path('', LoginView.as_view(), name='home-to-login'),
    path('company/', company_list, name='company_list'),
    path('company/<int:company_id>/', company_detail, name='company_detail'),
    path('company/create/', company_create, name='company_create'),
    path('company/<int:company_id>/update/', company_update, name='company_update'),
    path('company/<int:company_id>/delete/', company_delete, name='company_delete'),
    path('agent/<int:agent_id>/', agent_detail, name='agent_detail'),
    path('agent-lock/<int:agent_id>/', lock_agent, name='agent_lock_unlock'),
    path('cashier-create/<int:agent_id>/', cashier_create, name='cashier_create'),
    path('cashier-detail/<int:cashier_id>/', cashier_detail, name='cashier_detail'),
    path('change-password/', change_password, name='change_password'),
]

dashboard/models.py
from django.db import models

dashboard/views.py
import time
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views import View
from django.contrib.auth.models import Group, Permission
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_GET

from game_utils.auth_decorators import is_system_user, user_type_redirect
from dashboard.analyzer import get_initial_data
from dashboard.balance_sheet import get_agents_summary, get_statistics, get_total_statistics, ticket_statistics_area, truncate_decimal, zticket_statistics_area
from keno.models import Game, Ticket, GameResult
from game_utils.time_file import single_date
from zuser.forms import AgentForm, CompanyCreateForm
from zuser.models import Agent, Cashier, Company

User = get_user_model()


@method_decorator(user_type_redirect, name='dispatch')
class DashboardView(View):
    template_name = "dashboard/index.html"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
    def get(self, request, *args, **kwargs):
        self.context = self.get_context_data(request)
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        self.context = self.get_context_data(request)
        return render(request, self.template_name, self.context)

    def get_context_data(self, request):
        companies = Company.objects.all()
        agents = Agent.objects.all()
        cashiers = Cashier.objects.all()
        self.context = self.system(companies, agents) if is_system_user(request.user) else self.company(request, agents, cashiers)
        return self.context

    def company(self, request, agents, cashiers):
        daily_gain_loss_com = Ticket.objects.daily_total_gain_loss_com(request)
        weekly_gain_loss_com = Ticket.objects.weekly_total_gain_loss_com(request)
        initial_data = []
        start_time = time.time()
        all_agents_summary = get_agents_summary(request.user.company_user)
        end_time = time.time()
        elapsed_time = end_time - start_time
        print(f"Time taken to process get_agents_summary: {elapsed_time} seconds")
        for agent in agents:
            initial_data = get_initial_data(agent)
        statistics_area = ticket_statistics_area()
        zticket = zticket_statistics_area()
        print(f'zticket {zticket}')
        self.company_context = {
            'initial_data': initial_data,
            'form': CompanyCreateForm(),
            'total_cashiers':cashiers.count(),
            'total_agents':agents.count(),
            'daily_gain_loss': daily_gain_loss_com,
            'weekly_gain_loss': weekly_gain_loss_com,
            'all_agents_summary': all_agents_summary,
            'statistics_area': statistics_area,
            'zticket_statistics_area': zticket,
        }
        self.active_agents(request)
        return self.company_context

    def system(self, companies, agents):
        daily_gain_loss_sys = Ticket.objects.daily_total_gain_loss()
        weekly_gain_loss_sys = Ticket.objects.weekly_total_gain_loss()

        self.system_context = {
            'user_type': 'system',
            'add_type': 'Add System',
            'companies': companies,
            'agents': agents,
            'total_companies':companies.count(),
            'total_agents':agents.count(),
            'daily_gain_loss': daily_gain_loss_sys,
            'weekly_gain_loss': weekly_gain_loss_sys,
        }
        return self.system_context

    def active_agents(self, request):
        company_id = request.user.company_user
        open_agents = Company.objects.has_open(company_id)
        locked_agents = Company.objects.has_locked(company_id)
        all_agents = Company.objects.all_agents(company_id)
        all_cashiers = Agent.objects.filter_cashiers(company_id)
        open_agent_count = open_agents.count() if open_agents.count() > 0 else 0
        locked_agents_count = locked_agents.count() if locked_agents.count() > 0 else 0
        total_agents_count = all_agents.count() if all_agents.count() > 0 else 0
        total_cashiers_count = len(all_cashiers) if len(all_cashiers) > 0 else 0
        open_agent_count_perc = truncate_decimal((open_agent_count / total_agents_count) * 100) if total_agents_count > 0 else 0

        self.company_context.update({
            'total_cashiers_count': total_cashiers_count,
            'total_agent_count': total_agents_count,
            'open_agent_count': open_agent_count,
            'locked_agents_count': locked_agents_count,
            'open_agent_count_perc': open_agent_count_perc,
        })

    def perform_search(self, queryset):
        # Add your search logic here
        # Example: Searching based on a query parameter
        search_query = self.request.GET.get('search_query', '')
        if search_query:
            queryset = queryset.filter(your_search_field__icontains=search_query)
        return queryset

@method_decorator(user_type_redirect, name='dispatch')
class ManageCompanies(View):
    template_name = 'dashboard/manage_companies.html'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def get(self, request, *args, **kwargs):
        all_companies = Company.objects.all()
        companies_with_permissions = []
        for company in all_companies:
            agents = company.agents.all()
            permissions = company.company_user.user_permissions.values_list('codename', flat=True)
            groups = list(company.company_user.groups.values_list('name', flat=True)) or None
            companies_with_permissions.append({
                'company': company,
                'permissions': permissions,
                'groups': groups,
                'agents': agents,
            })

        self.context = {
            'companies': companies_with_permissions,
            'form': CompanyCreateForm(),
        }

        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):

        all_companies = Company.objects.all()
        companies_with_permissions = []
        for company in all_companies:
            agents = company.agents.all()
            permissions = company.company_user.user_permissions.values_list('codename', flat=True)
            groups = list(company.company_user.groups.values_list('name', flat=True)) or None
            companies_with_permissions.append({
                'company': company,
                'permissions': permissions,
                'groups': groups,
                'agents': agents,
            })

        self.context = {
            'companies': companies_with_permissions,
            'form': CompanyCreateForm(),
        }
        form = CompanyCreateForm(request.POST)
        if form.is_valid():
            form.save()
            form = CompanyCreateForm()
            self.context['form'] = form
            return redirect(reverse('dashboard:manage_company'))
        return render(request, self.template_name, self.context)

@method_decorator(user_type_redirect, name='dispatch')
class ManageAgents(View):
    template_name = 'dashboard/manage_agents.html'

    def get_form(self, request, data=None):
        company = request.user.company_user
        form = AgentForm(company, data)
        form.fields['company'].initial = company
        return form

    def get_all_agents(self, request):
        agents_list = Agent.objects.filter_agents_by_company(request.user.company_user)
        return [
            {
                'agent': agent,
            }
            for agent in agents_list
        ]

    def get(self, request, *args, **kwargs):
        form = self.get_form(request)
        self.context = {'form': form, 'agents': self.get_all_agents(request)}
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = self.get_form(request, request.POST)
        if form.is_valid():
            form.save()
            self.context = {'form': self.get_form(request), 'agents': self.get_all_agents(request)}
            return render(request, self.template_name, self.context)
        else:
            self.context = {'form': form, 'agents': self.get_all_agents(request)}
        return render(request, self.template_name, self.context)

@method_decorator(user_type_redirect, name='dispatch')
class ManageCashiers(View):
    template_name = 'dashboard/manage_cashiers.html'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.context = {'status': 'Active'}

    def get(self, request, *args, **kwargs):
        self.create_context(request)
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        selected_agent = request.POST.get('agents_list')
        print(selected_agent)
        if request.method == 'POST':
            agent = get_object_or_404(Agent, pk=selected_agent)
            cashiers = Cashier.objects.filter(agent=agent)
            cashier_count = cashiers.count()
            quantity = int(request.POST.get('quantity'))
            for q in range(quantity):
                username = f"{agent.full_name}.c{cashier_count + q}"
                username = username.replace(" ", "").lower()
                password = request.POST.get('pw')
                if User.objects.filter(username=username).exists():
                    username = f"{username}-{q}"
                user = User.objects.create_user(username=username, password=None)
                user.set_password(password)
                user.save()
                new_cashier = Cashier.objects.create(
                    cashier=user, agent=agent
                )

dashboard/templates/dashboard/Admin_Reports.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

dashboard/templates/dashboard/ShopAgent_Reports.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

dashboard/templates/dashboard/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

	<!-- Custom fonts for this template-->
	<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
		  rel="stylesheet">

	<!-- Custom styles for this template-->
	<link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this page -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'vendor/select2.css' %}" rel="stylesheet">
    {% block style %}
    {% endblock %}
    {% block chartscript %} 
    {% endblock %}
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

		{% include 'dashboard/includes/sidebar.html' %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
			
			{% include 'dashboard/includes/nav.html' %}
			
			{% block content %}
			{% endblock %}
			
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <form method="post" action="{% url 'zuser:logout' %}">
                        {% csrf_token %}
                        <button class="btn btn-danger" type="submit">Logout</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

	<!-- Bootstrap core JavaScript-->
	<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

	<!-- Core plugin JavaScript-->
	<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

	<!-- Custom scripts for all pages-->
	<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

	<!-- Page level plugins -->
	<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

	<!-- Page level custom scripts -->
	<script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="{% static 'vendor/select2.js' %}"></script>

{% block scripts %}
{% endblock %}
{% block jsScript %}
{% endblock %}
</body>

</html>

dashboard/templates/dashboard/base-auth.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% include 'includes/head.html' %}
  {% block extrastyle %}{% endblock extrastyle %}
</head>
<body>

  {% block content %}{% endblock content %}

  {% include 'includes/scripts.html' %}
  {% block extra_js %}{% endblock extra_js %}

</body>
</html>

dashboard/templates/dashboard/game-results.html
{% extends 'dashboard/_base.html' %}
{% load static %}

{% block content %}
<style>
    #dataTable_info, #dataTable_previous, #dataTable_next, .dataTables_empty{
        display: none;
    }
</style>
<!-- Begin Page Content -->
<div class="container-fluid">
    <div class="container mt-4">
        <!-- Form Section -->
        <form>
          <div class="form-row">
            <div class="form-group col-md-3">
              <label for="selectAgents">Select Agent</label>
              <select class="form-control" id="selectAgents" name="selectAgents">
                {% for agent in all_agents %}
                <option value="{{ agent.id }}">{{ agent.full_name }}</option>
                {% endfor %}
              </select>
            </div>
    
            <div class="form-group col-md-3">
              <label for="date">Date</label>
              <input type="date" class="form-control" id="date" name="date">
            </div>

            <div class="form-group col-md-3">
              <label for="submit">When you Finish</label>
              <button class="form-control text-lg btn btn-primary" type="submit">Load Tickets History</button>
            </div>
          </div>
        </form>
    
      </div>
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Shop Information</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive" id="dataTableContainer">
        <table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
          <thead class="bg-gradient-dark text-gray-100">
            <tr>
              <th>Shop</th>
              <th>Game ID</th>
              <th>Action</th>
              <th>Result</th>
            </tr>
          </thead>
          <tbody class="table-striped">
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script>
  $(document).ready(function() {
    $('form').submit(function(event) {
        event.preventDefault();
        var SelectedAgents = $('#selectAgents').val();
        var date = $('#date').val();
        $.ajax({
            type: 'GET',
            url: '{% url "dashboard:game_results_stats" %}',
            data: {
            selectAgent: SelectedAgents,
            date: date,
            },
            success: function(response) {
                console.log(response);
// Show the table
$('#dataTableContainer').show();
$('#dataTable').DataTable().clear().draw();

// Iterate over each game and its results
$.each(response.game_results, function(index, game) {
    // Create a row for the game
    var row = '<tr>' +
        '<td>' + game.shop + '</td>' +
        '<td>' + game.game_id + '</td>' +
        '<td>' + game.action + '</td>' +

        '<td>'; // Open the td element for result

        // Concatenate all results into one string
        $.each(game.result, function(idx, result) {
            row += result.value + ' '; // Append each result value followed by a space
        });

        row += '</td>'; 
    // Close the row
    row += '</tr>';

    // Append the row to the table
    $('#dataTable tbody').append(row);
});


            },
            error: function(xhr, status, error) {
            console.error('Error:', error);
            }
        });
        });

  });
</script>
{% endblock %}

dashboard/templates/dashboard/gamer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Chrome App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<link href="{% static 'css/gamer.css' %}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <div id="balls" class="container">
            <!-- Balls content goes here -->
            <h1>Balls Section</h1>
            <div id="balls-grid" class="row"></div>
        </div>
        <div id="time" class="container">
            <!-- Time content goes here -->
            <h1>Time Section</h1>
            <div id="timer">04:00</div>
        </div>
    </div>

	<script src="{% static 'js/gamer.js' %}"></script>
</body>
</html>

dashboard/templates/dashboard/manage_agents.html
{% extends "dashboard/_base.html" %}
{% load static %}
{% block content %}
<style>
    a.text-lg {
    text-decoration: none;
}
</style>
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Agent Table</h1>
        <a href="#" data-toggle="modal" data-target="#registrationModal">
            <button type="submit" class="btn btn-primary mt-4">
                <i class="fas fa-plus fa-sm text-white-50"></i> 
                Add Agent 
            </button>
        </a>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3"> 
            <h6 class="m-0 font-weight-bold text-primary">Agents Overview</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th style="color: #ffffff; background-color: #007bff;">Name</th>
                            <th style="color: #ffffff; background-color: #007bff;">Address</th>
                            <th style="color: #ffffff; background-color: #007bff;">Phone Number</th>
                            <th style="color: #ffffff; background-color: #007bff;">Capital</th>
                            <th style="color: #ffffff; background-color: #007bff;">margin</th>
                            <th style="color: #ffffff; background-color: #007bff;">Locked</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for agent in agents %}
                        {% with ag=agent.agent %}
                        <tr>
                            <td><a class="text-lg" style="width: 100%;" href="{{ ag.get_absolute_url }}">{{ ag }}</a></td>
                            <td>{{ ag.agent_address }}</td>
                            <td>{{ ag.phone_number }}</td>
                            <td>{{ ag.agent_capital }}</td>
                            <td>{{ ag.agent_margin }}</td>
                            <td>
                                <form action="{% url 'zuser:agent_lock_unlock' agent_id=ag.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn {% if ag.locked %}btn-danger{% else %}btn-success{% endif %}">
                                        {% if ag.locked %}Unlock{% else %}Lock{% endif %}
                                    </button>
                                </form>
                            </td>
                        </tr>
                        {% endwith %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->

<!-- Registration Modal -->
<div class="modal fade" id="registrationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Agent Registration</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'dashboard:manage_agent' %}" method="post">
                    <!-- Step 1: Personal Information -->
                    <div id="step1">
                        {{ form.full_name.label_tag }}
                        {{ form.full_name }}
                        {{ form.full_name.errors }}
                        {{ form.phone_number.label_tag }}
                        {{ form.phone_number }}
                        {{ form.phone_number.errors }}
                    </div>
                
                    <!-- Step 2: Address Information -->
                    <div id="step2" style="display: none;">
                        {{ form.agent_capital.label_tag }}
                        {{ form.agent_capital }}
                        {{ form.agent_capital.errors }}
                        {{ form.agent_address.label_tag }}
                        {{ form.agent_address }}
                        {{ form.agent_address.errors }}
                
                        <!-- Display error for the hidden field 'company' -->
                        {{ form.company.errors }}
                
                        {{ form.company }}
                        <input type="hidden" name="action" value="agent">
                        <button type="submit" class="btn btn-primary mt-4">
                             Submit
                        </button>
                    </div>
                    {% csrf_token %}
                </form>
                
            </div>
            <div class="modal-footer">
                <!-- Navigation buttons for steps -->
                <button class="btn btn-secondary" onclick="showStep(1)">Previous</button>
                <button class="btn btn-primary" onclick="showStep(2)">Next</button>
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<script>
    function showPStep(stepNumber) {
        for (let i = 1; i <= 2; i++) {
            document.getElementById('Pstep' + i).style.display = 'none';
        }
        document.getElementById('Pstep' + stepNumber).style.display = 'block';
        if (stepNumber === 1) {
            document.querySelector('.modal-footer button:nth-child(2)').style.display = 'block';
            document.querySelector('.modal-footer button:nth-child(3)').style.display = 'none';
        } else if (stepNumber === 2) {
            document.querySelector('.modal-footer button:nth-child(2)').style.display = 'none';
            document.querySelector('.modal-footer button:nth-child(3)').style.display = 'block';
        }
    }

    function showStep(stepNumber) {
        for (let i = 1; i <= 2; i++) {
            document.getElementById('step' + i).style.display = 'none';
        }
        document.getElementById('step' + stepNumber).style.display = 'block';
        if (stepNumber === 1) {
            document.querySelector('.modal-footer button:nth-child(2)').style.display = 'block';
            document.querySelector('.modal-footer button:nth-child(3)').style.display = 'none';
        } else if (stepNumber === 2) {
            document.querySelector('.modal-footer button:nth-child(2)').style.display = 'none';
            document.querySelector('.modal-footer button:nth-child(3)').style.display = 'block';
        }
    }

    function submitForm(event) {
        // Prevent the default form submission behavior
        event.preventDefault();

        // Get the form data
        const formData = new FormData(document.querySelector('form'));

        // Make a fetch request to submit the form data
        fetch('/dashboard/manage-agent/', {
            method: 'POST',
            body: formData,
        })
        .then(response => {
            if (response.ok) {
                // Handle success, e.g., update UI or show a success message
                alert('Form submitted successfully');
                $('#registrationModal').modal('hide');
            } else {
                // Handle errors, e.g., show an error message
                alert('Form submission failed');
            }
        })
        .catch(error => {
            // Handle network errors
            console.error('Error:', error);
        });
    }

</script>

{% endblock %}