dashboard/urls.py
from django.urls import path
from .views import (DashboardView, tickets_view, tickets_statistics_view, game_results_view, game_result_stats_view, shop_reports,
                    ManageCompanies, ManageUserPermissionsView,
                    ManageAgents, ManageCashiers, agents_statistics_view)

app_name = 'dashboard'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard_view'),
    path('manage-company/', ManageCompanies.as_view(), name='manage_company'),
    path('manage-agent/', ManageAgents.as_view(), name='manage_agent'),
    path('manage-cashier/', ManageCashiers.as_view(), name='manage_cashier'),
    path('manage-permission-group/<int:user_id>/', ManageUserPermissionsView.as_view(), name='manage_permission_group'),
    path('tickets/', tickets_view, name='tickets'),
    path('tickets-statistics/', tickets_statistics_view, name='tickets_statistics'),
    path('game-results/', game_results_view, name='game_results'),
    path('game-stats/', game_result_stats_view, name='game_results_stats'),
    path('shop-reports/', shop_reports, name='shop_agent_reports'),
    path('api-statistics/', agents_statistics_view, name='api_statistics'),
]

game/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from spin.views import keno_update_view, spin_update_view

urlpatterns = [
    path('', include('cashierapp.urls')),
    path('api/', include('keno.api.urls')),
    path('spin/', include('spin.api.urls')),
    # path('users/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('zuser/', include('zuser.urls')),
    path('mobile/', include('mobile.urls')),
    path('admin/', admin.site.urls),
    path('keno-update-view/', keno_update_view, name='kuv'),
    path('spin-update-view/', spin_update_view, name='suv'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         path('debug/', include(debug_toolbar.urls)),
#     ]

# if not settings.DEBUG:
#     urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/models.py
from django.db import models

dashboard/views.py
import time
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views import View
from django.contrib.auth.models import Group, Permission
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_GET

from game_utils.auth_decorators import is_system_user, user_type_redirect
from dashboard.analyzer import get_initial_data
from dashboard.balance_sheet import get_agents_summary, get_statistics, get_total_statistics, ticket_statistics_area, truncate_decimal, zticket_statistics_area
from keno.models import Game, Ticket, GameResult
from game_utils.time_file import single_date
from zuser.forms import AgentForm, CompanyCreateForm
from zuser.models import Agent, Cashier, Company

User = get_user_model()


@method_decorator(user_type_redirect, name='dispatch')
class DashboardView(View):
    template_name = "dashboard/index.html"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
    def get(self, request, *args, **kwargs):
        self.context = self.get_context_data(request)
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        self.context = self.get_context_data(request)
        return render(request, self.template_name, self.context)

    def get_context_data(self, request):
        companies = Company.objects.all()
        agents = Agent.objects.all()
        cashiers = Cashier.objects.all()
        self.context = self.system(companies, agents) if is_system_user(request.user) else self.company(request, agents, cashiers)
        return self.context

    def company(self, request, agents, cashiers):
        daily_gain_loss_com = Ticket.objects.daily_total_gain_loss_com(request)
        weekly_gain_loss_com = Ticket.objects.weekly_total_gain_loss_com(request)
        initial_data = []
        start_time = time.time()
        all_agents_summary = get_agents_summary(request.user.company_user)
        end_time = time.time()
        elapsed_time = end_time - start_time
        print(f"Time taken to process get_agents_summary: {elapsed_time} seconds")
        for agent in agents:
            initial_data = get_initial_data(agent)
        statistics_area = ticket_statistics_area()
        zticket = zticket_statistics_area()
        print(f'zticket {zticket}')
        self.company_context = {
            'initial_data': initial_data,
            'form': CompanyCreateForm(),
            'total_cashiers':cashiers.count(),
            'total_agents':agents.count(),
            'daily_gain_loss': daily_gain_loss_com,
            'weekly_gain_loss': weekly_gain_loss_com,
            'all_agents_summary': all_agents_summary,
            'statistics_area': statistics_area,
            'zticket_statistics_area': zticket,
        }
        self.active_agents(request)
        return self.company_context

    def system(self, companies, agents):
        daily_gain_loss_sys = Ticket.objects.daily_total_gain_loss()
        weekly_gain_loss_sys = Ticket.objects.weekly_total_gain_loss()

        self.system_context = {
            'user_type': 'system',
            'add_type': 'Add System',
            'companies': companies,
            'agents': agents,
            'total_companies':companies.count(),
            'total_agents':agents.count(),
            'daily_gain_loss': daily_gain_loss_sys,
            'weekly_gain_loss': weekly_gain_loss_sys,
        }
        return self.system_context

    def active_agents(self, request):
        company_id = request.user.company_user
        open_agents = Company.objects.has_open(company_id)
        locked_agents = Company.objects.has_locked(company_id)
        all_agents = Company.objects.all_agents(company_id)
        all_cashiers = Agent.objects.filter_cashiers(company_id)
        open_agent_count = open_agents.count() if open_agents.count() > 0 else 0
        locked_agents_count = locked_agents.count() if locked_agents.count() > 0 else 0
        total_agents_count = all_agents.count() if all_agents.count() > 0 else 0
        total_cashiers_count = len(all_cashiers) if len(all_cashiers) > 0 else 0
        open_agent_count_perc = truncate_decimal((open_agent_count / total_agents_count) * 100) if total_agents_count > 0 else 0

        self.company_context.update({
            'total_cashiers_count': total_cashiers_count,
            'total_agent_count': total_agents_count,
            'open_agent_count': open_agent_count,
            'locked_agents_count': locked_agents_count,
            'open_agent_count_perc': open_agent_count_perc,
        })

    def perform_search(self, queryset):
        # Add your search logic here
        # Example: Searching based on a query parameter
        search_query = self.request.GET.get('search_query', '')
        if search_query:
            queryset = queryset.filter(your_search_field__icontains=search_query)
        return queryset

@method_decorator(user_type_redirect, name='dispatch')
class ManageCompanies(View):
    template_name = 'dashboard/manage_companies.html'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def get(self, request, *args, **kwargs):
        all_companies = Company.objects.all()
        companies_with_permissions = []
        for company in all_companies:
            agents = company.agents.all()
            permissions = company.company_user.user_permissions.values_list('codename', flat=True)
            groups = list(company.company_user.groups.values_list('name', flat=True)) or None
            companies_with_permissions.append({
                'company': company,
                'permissions': permissions,
                'groups': groups,
                'agents': agents,
            })

        self.context = {
            'companies': companies_with_permissions,
            'form': CompanyCreateForm(),
        }

        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):

        all_companies = Company.objects.all()
        companies_with_permissions = []
        for company in all_companies:
            agents = company.agents.all()
            permissions = company.company_user.user_permissions.values_list('codename', flat=True)
            groups = list(company.company_user.groups.values_list('name', flat=True)) or None
            companies_with_permissions.append({
                'company': company,
                'permissions': permissions,
                'groups': groups,
                'agents': agents,
            })

        self.context = {
            'companies': companies_with_permissions,
            'form': CompanyCreateForm(),
        }
        form = CompanyCreateForm(request.POST)
        if form.is_valid():
            form.save()
            form = CompanyCreateForm()
            self.context['form'] = form
            return redirect(reverse('dashboard:manage_company'))
        return render(request, self.template_name, self.context)

@method_decorator(user_type_redirect, name='dispatch')
class ManageAgents(View):
    template_name = 'dashboard/manage_agents.html'

    def get_form(self, request, data=None):
        company = request.user.company_user
        form = AgentForm(company, data)
        form.fields['company'].initial = company
        return form

    def get_all_agents(self, request):
        agents_list = Agent.objects.filter_agents_by_company(request.user.company_user)
        return [
            {
                'agent': agent,
            }
            for agent in agents_list
        ]

    def get(self, request, *args, **kwargs):
        form = self.get_form(request)
        self.context = {'form': form, 'agents': self.get_all_agents(request)}
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = self.get_form(request, request.POST)
        if form.is_valid():
            form.save()
            self.context = {'form': self.get_form(request), 'agents': self.get_all_agents(request)}
            return render(request, self.template_name, self.context)
        else:
            self.context = {'form': form, 'agents': self.get_all_agents(request)}
        return render(request, self.template_name, self.context)

@method_decorator(user_type_redirect, name='dispatch')
class ManageCashiers(View):
    template_name = 'dashboard/manage_cashiers.html'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.context = {'status': 'Active'}

    def get(self, request, *args, **kwargs):
        self.create_context(request)
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        selected_agent = request.POST.get('agents_list')
        print(selected_agent)
        if request.method == 'POST':
            agent = get_object_or_404(Agent, pk=selected_agent)
            cashiers = Cashier.objects.filter(agent=agent)
            cashier_count = cashiers.count()
            quantity = int(request.POST.get('quantity'))
            for q in range(quantity):
                username = f"{agent.full_name}.c{cashier_count + q}"
                username = username.replace(" ", "").lower()
                password = request.POST.get('pw')
                if User.objects.filter(username=username).exists():
                    username = f"{username}-{q}"
                user = User.objects.create_user(username=username, password=None)
                user.set_password(password)
                user.save()
                new_cashier = Cashier.objects.create(
                    cashier=user, agent=agent
                )

dashboard/templates/dashboard/includes/head.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

dashboard/templates/dashboard/includes/nav.html
{% load static %}
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

	<!-- Sidebar Toggle (Topbar) -->
	<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
		<i class="fa fa-bars"></i>
	</button>

	<!-- Header -->
	<div class="p-5 navbar-header">
		<a class="navbar-brand" href="{% url 'dashboard:dashboard_view' %}">
			<span>{{ request.user.first_name }} {{ request.user.last_name }}</span>
		</a>
	</div>

	<div class="ml-auto btn btn-danger">
		<a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
			<i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-white"></i>
			Logout
		</a>
	</div>
</nav>
<!-- End of Topbar -->

dashboard/templates/dashboard/includes/sidebar.html
{% load static %}
<style>
    /* Adjust font sizes */
    .sidebar-brand-text {
        font-size: 1.2rem; /* Increase sidebar brand text size */
    }

    .nav-link,
    .font-weight-bold {
        font-size: 1rem !important; /* Increase font size for links and bold text */
    }

    /* Reduce padding between nav items */
    .nav-item {
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
    }

    /* Reduce spacing between sidebar items */
    .nav-item:not(:last-child) {
        margin-bottom: 0.5rem;
    }

    /* Reduce spacing between sidebar divider and items */
    .sidebar-divider {
        margin: 0.5rem 0;
    }

    /* Reduce top and bottom margins of sidebar toggle button */
    #sidebarToggle {
        margin-top: 1rem;
        margin-bottom: 1rem;
    }
</style>
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'dashboard:dashboard_view' %}">
        <div class="sidebar-brand-icon rotate-n-15">
            <img src="{% static 'img/mayabets_logo.jpg' %}" alt="Logo" style="max-height: 50px; border-radius: 50%;">
        </div>
        <div class="sidebar-brand-text mx-3">Dashboard</div>
    </a>

    <li class="nav-item">      
        <a class="nav-link" href="{% url 'dashboard:shop_agent_reports' %}">
            <i class="fas fa-chart-bar mr-2"></i> <span class="font-weight-bold">Shop/Agent Reports</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:tickets' %}">
            <i class="fas fa-ticket-alt mr-2"></i> <span class="font-weight-bold">Tickets</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:game_results' %}">
            <i class="fas fa-dice mr-2"></i> <span class="font-weight-bold">Game Results</span>
        </a>
    </li>
{% if user.is_staff %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'dashboard:manage_company' %}">
        <i class="fas fa-users mr-2"></i> <span class="font-weight-bold">Company Users</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{% url 'dashboard:manage_agent' %}">
        <i class="fas fa-users mr-2"></i> <span class="font-weight-bold">Agent Users</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{% url 'dashboard:manage_cashier' %}">
        <i class="fas fa-users mr-2"></i> <span class="font-weight-bold">Cashier Users</span>
    </a>
</li>

{% else %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'dashboard:manage_cashier' %}">
        <i class="fas fa-users mr-2"></i> <span class="font-weight-bold">Cashier Users</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{% url 'dashboard:manage_agent' %}">
        <i class="fas fa-users mr-2"></i> <span class="font-weight-bold">Agent Users</span>
    </a>
</li>
{% endif %}

    <hr class="sidebar-divider">

    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>