dashboard/urls.py
from django.urls import path
from .views import (DashboardView, tickets_view, tickets_statistics_view, game_results_view, game_result_stats_view, shop_reports,
                    ManageCompanies, ManageUserPermissionsView,
                    ManageAgents, ManageCashiers, agents_statistics_view)

app_name = 'dashboard'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard_view'),
    path('manage-company/', ManageCompanies.as_view(), name='manage_company'),
    path('manage-agent/', ManageAgents.as_view(), name='manage_agent'),
    path('manage-cashier/', ManageCashiers.as_view(), name='manage_cashier'),
    path('manage-permission-group/<int:user_id>/', ManageUserPermissionsView.as_view(), name='manage_permission_group'),
    path('tickets/', tickets_view, name='tickets'),
    path('tickets-statistics/', tickets_statistics_view, name='tickets_statistics'),
    path('game-results/', game_results_view, name='game_results'),
    path('game-stats/', game_result_stats_view, name='game_results_stats'),
    path('shop-reports/', shop_reports, name='shop_agent_reports'),
    path('api-statistics/', agents_statistics_view, name='api_statistics'),
]

game/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from spin.views import keno_update_view, spin_update_view

urlpatterns = [
    path('', include('cashierapp.urls')),
    path('api/', include('keno.api.urls')),
    path('spin/', include('spin.api.urls')),
    # path('users/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('zuser/', include('zuser.urls')),
    path('mobile/', include('mobile.urls')),
    path('admin/', admin.site.urls),
    path('keno-update-view/', keno_update_view, name='kuv'),
    path('spin-update-view/', spin_update_view, name='suv'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         path('debug/', include(debug_toolbar.urls)),
#     ]

# if not settings.DEBUG:
#     urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

zuser/urls.py
from django.urls import path, include
# from allauth.account.views import LoginView

from .views import (
	company_list, lock_agent,
	company_detail, 
	company_create, 
	company_update, 
	company_delete, agent_detail, cashier_create, cashier_detail, login_view,
    signup_view, forgot_password_view,create_superuser_view, logout_view, change_password)
app_name = 'zuser'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', signup_view, name='signup'),
    path('forgot-password/', forgot_password_view, name='forgot_password'),
    path('create-superuser/', create_superuser_view, name='create_superuser'),
    path('logout/', logout_view, name='logout'),
    # path('', LoginView.as_view(), name='home-to-login'),
    path('company/', company_list, name='company_list'),
    path('company/<int:company_id>/', company_detail, name='company_detail'),
    path('company/create/', company_create, name='company_create'),
    path('company/<int:company_id>/update/', company_update, name='company_update'),
    path('company/<int:company_id>/delete/', company_delete, name='company_delete'),
    path('agent/<int:agent_id>/', agent_detail, name='agent_detail'),
    path('agent-lock/<int:agent_id>/', lock_agent, name='agent_lock_unlock'),
    path('cashier-create/<int:agent_id>/', cashier_create, name='cashier_create'),
    path('cashier-detail/<int:cashier_id>/', cashier_detail, name='cashier_detail'),
    path('change-password/', change_password, name='change_password'),
]

zuser/forms.py
# forms.py

from django import forms
from .models import Company, Agent, Player


class ChangePasswordForm(forms.Form):
    new_password = forms.CharField(label='New Password', widget=forms.PasswordInput)
    confirm_new_password = forms.CharField(label='Confirm New Password', widget=forms.PasswordInput)

class CompanyCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CompanyCreateForm, self).__init__(*args, **kwargs)

        # Add form-control class and placeholders
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

            # Adding placeholders for each field
            placeholders = {
                'company_user': 'Enter company user',
                'company_address': 'Enter company address',
                'company_phone_number': 'Enter phone number',
                'company_capital': 'Enter company capital',
                'subscription_start': 'Enter subscription start date',
                'subscription_end': 'Enter subscription end date',
            }

            field.widget.attrs['placeholder'] = placeholders.get(field_name, '')

    class Meta:
        model = Company
        fields = ['company_user', 'company_address', 
                  'company_phone_number', 'company_capital', 
                  'subscription_start', 'subscription_end']


class CompanyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)

        # Add form-control class and placeholders
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

            # Adding placeholders for each field
            placeholders = {
                'company_user': 'Enter company user',
                'company_address': 'Enter company address',
                'company_phone_number': 'Enter phone number',
                'company_capital': 'Enter company capital',
                'subscription_start': 'Enter subscription start date',
                'subscription_end': 'Enter subscription end date',
            }

            field.widget.attrs['placeholder'] = placeholders.get(field_name, '')

    class Meta:
        model = Company
        fields = ['company_user', 'company_address', 
                  'company_phone_number', 'company_capital', 
                  'subscription_start', 'subscription_end']
        exclude = ['company_user']


class AgentForm(forms.ModelForm):
    class Meta:
        model = Agent
        fields = ['full_name', 'company', 'agent_capital', 'phone_number', 'agent_address', 'keno_margin', 'locked']
        # exclude = ['agent_user']
        # widgets = {
        #     'locked': forms.CheckboxInput(attrs={'class': 'form-check-input'})
        # }

    def __init__(self, company, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['company'].widget = forms.HiddenInput()
        self.company = company
        for field_name, field in self.fields.items():
            if field_name != 'locked':
                field.widget.attrs.update({'class': 'form-control', 'placeholder': f'Enter {field_name}'})

class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ['player']

zuser/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from django.contrib.auth import get_user_model, logout, authenticate, login
from django.contrib.auth.forms import PasswordResetForm, UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.utils.decorators import method_decorator
from game_utils.auth_decorators import user_type_redirect
from .models import Company, Agent, Cashier, Player
from .forms import CompanyForm, AgentForm, ChangePasswordForm

def create_superuser_view(request):
    template_name = 'account/create_superuser.html'
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # Redirect to some page indicating successful superuser creation
            return redirect('/admin')
    else:
        form = UserCreationForm()
    return render(request, template_name, {'form': form})

def logout_view(request):
    logout(request)
    # Redirect to some page after logout
    return redirect('/zuser/login/')  # Replace 'index' with the name of your desired page

def signup_view(request):
    success_url_name = '/mobile/'
    template_name = 'registration/signup.html'
    form_class = UserCreationForm

    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            user = form.save()
            # Create a Player associated with the newly created user
            Player.objects.create(player=user)
            # Redirect to login page or some other page after successful account creation
            return redirect(success_url_name)
    else:
        form = form_class()

    # Add 'form-control' class to form fields
    for field in form.fields.values():
        field.widget.attrs.update({'class': 'form-control'})

    # Add placeholders to the fields
    form.fields['username'].widget.attrs['placeholder'] = 'Username'
    form.fields['password1'].widget.attrs['placeholder'] = 'Password'
    form.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'

    return render(request, template_name, {'form': form})

def forgot_password_view(request):
    success_url_name = '/users/login'
    template_name = 'account/forgot_password2.html'
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            form.save()
            # Redirect to password reset done page
            return redirect(success_url_name)
    else:
        form = PasswordResetForm()
    return render(request, template_name, {'form': form})

def login_view(request):
    template_name = 'registration/new_login.html'
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_staff:
                    return redirect('/admin')
                login(request, user)
                #messages.success(request, f"Success: Login Successful!")
                return redirect(reverse("cashierapp:cashier_url"))
        else:
            messages.error(request, f"Error: Invalid username or password!")
            return redirect('zuser:login')
    else:
        form = AuthenticationForm(request)
    return render(request, template_name, {'form': form})

# @method_decorator(user_type_redirect, name='dispatch')
def change_password(request):
    cashier_id = request.GET.get('cashier_id')
    cashier = get_object_or_404(Cashier, pk=cashier_id)
    user = cashier.cashier

    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            confirm_new_password = form.cleaned_data['confirm_new_password']
            if new_password == confirm_new_password:
                user.set_password(new_password)
                user.save()
                messages.success(request, 'Password changed successfully.')
            else:
                messages.error(request, 'Passwords do not match.')
            return JsonResponse({'messages': messages})
    else:
        print('change password GET')
        pass

def cashier_detail(request, cashier_id):
    cashier = get_object_or_404(Cashier, pk=cashier_id)
    user = cashier.cashier

    if request.method == 'POST':
        cashier_name = request.POST.get('cashier_name')
        password = request.POST.get('password')
        has_access = request.POST.get('has_access')
        user.username = cashier_name
        if password:
            user.set_password(password)
        if has_access == 'on':
            cashier.has_access = True
        else:
            cashier.has_access = False
        cashier.save()
        user.save()
        messages.success(request, 'Cashier information updated successfully.')
        return redirect('zuser:cashier_detail', cashier_id=cashier.id)
    return render(request, 'zuser/cashier_detail.html', {'cashier': cashier})

def lock_agent(request, agent_id):
    agent = get_object_or_404(Agent, pk=agent_id)
    if request.method == 'POST':
        agent.locked = False if agent.locked else True
        agent.save()
        return redirect(reverse('dashboard:manage_agent'))

def agent_detail(request, agent_id):
    agent = get_object_or_404(Agent, pk=agent_id)
    user_company = agent.company
    cashiers = Cashier.objects.filter(agent=agent)
    if request.method == 'POST':
        form = AgentForm(user_company, request.POST)
        if form.is_valid():
            # form.cleaned_data['agent_user'] = agent
            form.save()
            return redirect(reverse('dashboard:manage_agent'))
        else:
            pass
    else:
        form = AgentForm(user_company, instance=agent)
        pw_form =  ChangePasswordForm()
        return render(request, 'zuser/cashier_list.html', {'agent': agent, 'form': form, 'cashiers': cashiers, 'pw_form': pw_form})

def cashier_create(request, agent_id):
    if request.method == 'POST':
        agent = get_object_or_404(Agent, pk=agent_id)
        cashiers = Cashier.objects.filter(agent=agent)
        print(cashiers)
        cashier_count = cashiers.count() if cashiers else 0
        print(cashier_count)
        quantity = int(request.POST.get('quantity'))
        User = get_user_model()
        phone = agent.phone_number
        for q in range(quantity):
            username = f"{agent.full_name}.c{cashier_count + q}"
            username = username.replace(" ", "").lower()
            password = request.POST.get('pw')
            if User.objects.filter(username=username).exists():
                username = f"{username}-{q}"

            # Create user without setting the password directly
            user = User.objects.create_user(username=username, password=None)
            user.set_password(password)  # Set password separately
            user.save()  # Save user after setting password

            new_cashier = Cashier.objects.create(
                cashier=user, agent=agent
            )
            print(f'user: {user}, new_cashier: {new_cashier}')
    return redirect('dashboard:manage_agent')

def company_list(request):
    companies = Company.objects.all()
    return render(request, 'zuser/company_list.html', {'companies': companies})

@method_decorator(user_type_redirect, name='dispatch')
def company_detail(request, company_id):
    company = get_object_or_404(Company, pk=company_id)
    if request.method == 'POST':
        form = CompanyForm(request.POST, instance=company)
        if form.is_valid():
            form.save()
            return redirect(reverse('dashboard:manage_company'))
    else:
        form = CompanyForm(instance=company)
    context = {'company': company, 'form': form}
    return render(request, 'zuser/company_detail.html', context)


def company_create(request):
    if request.method == 'POST':
        form = CompanyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('company_list')
    else:
        form = CompanyForm()
    return render(request, 'zuser/company_form.html', {'form': form})


def company_update(request, company_id):
    company = get_object_or_404(Company, pk=company_id)
    if request.method == 'POST':
        form = CompanyForm(request.POST, instance=company)
        if form.is_valid():
            form.save()
            return redirect('company_list')
    else:
        form = CompanyForm(instance=company)
    return render(request, 'zuser/company_form.html', {'form': form})


def company_delete(request, company_id):
    company = get_object_or_404(Company, pk=company_id)
    if request.method == 'POST':
        company.delete()
        return redirect('company_list')
    return render(request, 'zuser/company_confirm_delete.html', {'company': company})


# def loginview(request):
#     return render(request, 'zuser/login.html')

zuser/templates/zuser/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>
<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">

{% block content %}

{% endblock %}

                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- End of Page Wrapper -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    {% block script %}
    {% endblock %}

</body>

</html>

zuser/templates/zuser/cashier_detail.html
{% extends "dashboard/_base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Cashier Detail</h6>
        </div>
                <div class="card-body">
                    <form method="post" action=".">
                        {% csrf_token %}
                        <div class="form-row">
                            <input type="hidden" class="form-control" id="cashier_id" name="cashier_id" value="{{ cashier.id }}" readonly>
                            <div class="form-group col-md-12">
                                <label for="cashier_name"{% if cashier.has_access %} class="text-primary"{% endif %}>{% if cashier.has_access %}Admin Cashier{% else %}Cashier Name:{% endif %}</label>
                                <input type="text" class="form-control" id="cashier_name" name="cashier_name" value="{{ cashier.cashier }}">
                            </div>
                            <div class="form-group col-md-12">
                                <label for="agent">Agent:</label>
                                <input type="text" class="form-control" id="agent" name="agent" value="{{ cashier.agent }}" readonly>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="password">Change Password:</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="*********">
                            </div>
                            <div class="form-group col-md-6">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="has_access" name="has_access" {% if cashier.has_access %}checked{% endif %}>
                                    <label class="form-check-label" for="has_access">
                                        Has Admin Access
                                    </label>
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                <button type="submit" class="form-control btn btn-primary">Update</button>
                            </div>
                        </div>
                    </form>
                
    </div>
</div>
</div>
<div class="col-md-2"></div>
</div>
</div>
{% endblock %}

zuser/templates/zuser/cashier_list.html
{% extends "dashboard/_base.html" %}
{% load static %}
{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">
    <div class="row">
        <!-- Form -->
        <div class="col-md-6">
            <!-- Page Heading -->
            <h1 class="h3 mb-4 text-gray-800">{{ agent.first_name }}</h1>
            
            <h2>
                Update profile
            </h2>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="form-control btn btn-success" type="submit">Update</button>
            </form>
        </div>

        <!-- Cashiers List -->
        <div class="col-md-6">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Table</h1>
                <a href="#" data-toggle="modal" data-target="#registrationModal">
                    <button type="submit" class="btn btn-primary mt-4">
                        <i class="fas fa-plus fa-sm text-white-50"></i> 
                        Add Cashier 
                    </button>
                </a>
            </div>

            <div class="card shadow mb-4">
                <div class="card-header py-3"> 
                    <h6 class="m-0 font-weight-bold text-primary">Cashiers List</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                            <th>Cashier</th>
                            <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cashier in cashiers %}
                        <tr>
                            <td{% if cashier.has_access %} class="text-primary"{% endif %}>{{ cashier.cashier }}</td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Actions
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item btn btn-primary" href="{% url 'zuser:cashier_detail' cashier.id %}">Details</a>
                                        <button type="button" class="dropdown-item btn btn-primary" data-toggle="modal" data-target="#changePasswordModal" data-cashier-id="{{ cashier.id }}">Change Password</button>
                                        <a class="dropdown-item btn btn-danger" href=" url 'zuser:deactivate' cashier.id %}">Deactivate</a>
                                        <a class="dropdown-item btn btn-success" href=" url 'zuser:make_admin' cashier.id %}">Make Admin</a>
                                        <!-- Add more dropdown items as needed -->
                                    </div>
                                </div>
                            </td>
                        </tr>
                            {% endfor %}
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
<!-- Modal -->
<!-- Modal for Change Password -->
<div class="modal fade" id="changePasswordModal" tabindex="-1" role="dialog" aria-labelledby="changePasswordModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="changePasswordModalLabel">Change Password</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <!-- Form for changing password -->
          <form id="changePasswordForm" method="post" action="">
            {% csrf_token %}
            <input type="hidden" id="cashierIdInput" name="cashier_id">
            <div class="form-group">
              <label for="inputPassword">New Password</label>
              <input type="password" class="form-control" id="inputPassword" name="new_password" required>
            </div>
            <div class="form-group">
              <label for="inputConfirmPassword">Confirm New Password</label>
              <input type="password" class="form-control" id="inputConfirmPassword" name="confirm_new_password" required>
            </div>
            <button type="submit" class="btn btn-primary">Change Password</button>
          </form>
        </div>
      </div>
    </div>
  </div>


<!-- Registration Modal -->
<div class="modal fade" id="registrationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Agent Registration</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <h1>Create Cashiers</h1>
                <form action="{% url 'zuser:cashier_create' agent.id %}" method="post">

                    <label for="cashiers_quantity">Cashiers Quantity:</label>
                    <div class="input-group">
                        <input class="form-control" min="1" required type="number" id="cashiers_quantity" name="quantity">
                    </div>

                    <div class="input-group">
                        <input value="qwerty123456" type="pw" id="pw" name="pw" class="form-control" aria-describedby="pw-toggle">
                        <button class="btn btn-outline-secondary" type="button" id="pw-toggle" onclick="togglePasswordVisibility()">Show</button>
                    </div>
                    <input type="hidden" name="action" value="agent">
                    <button type="submit" class="btn btn-primary mt-4">
                        Create Cashiers
                    </button>
                    {% csrf_token %}
                </form>
                
            </div>
            <div class="modal-footer">
                <!-- Navigation buttons for steps -->
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<script>

    function submitForm(event) {
        // Prevent the default form submission behavior
        event.preventDefault();

        // Get the form data
        const formData = new FormData(document.querySelector('form'));

        // Make a fetch request to submit the form data
        fetch('/dashboard/cashier-create/', {
            method: 'POST',
            body: formData,
        })
        .then(response => {
            if (response.ok) {
                // Handle success, e.g., update UI or show a success message
                alert('Form submitted successfully');
                $('#registrationModal').modal('hide');
            } else {
                // Handle errors, e.g., show an error message
                alert('Form submission failed');
            }
        })
        .catch(error => {
            // Handle network errors
            console.error('Error:', error);
        });
    }

    function togglePasswordVisibility() {
        var passwordInput = document.getElementById("pw");
        var passwordToggleBtn = document.getElementById("pw-toggle");

        if (passwordInput.type === "pw") {
            passwordInput.type = "text";
            passwordToggleBtn.textContent = "Hide";
        } else {
            passwordInput.type = "pw";
            passwordToggleBtn.textContent = "Show";
        }
    }
</script>

{% endblock %}
    
{% block script %}
  <script>
    $('#changePasswordModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget); // Button that triggered the modal
        var cashierId = button.data('cashier-id'); // Extract info from data-* attributes
        var modal = $(this);
        modal.find('#cashierIdInput').val(cashierId); // Set the value of the hidden input field
        alert(cashierId);
        modal.find('form').attr('action', '{% url 'zuser:change_password' %}'); // Set the form action URL
    });
</script>
  
    {% endblock %}

zuser/templates/zuser/login.html
{% extends 'zuser/_base.html' %}
{% load static %}

{% block content %}

<h3><a href="{% url 'zuser:login' %}">Login</a></h3>
<h3><a href="{% url 'zuser:logout' %}">logout</a></h3>
<h3><a href="{% url 'account_signup' %}">signup</a></h3>
<h3><a href="{% url 'account_change_password' %}">change password</a></h3>


<div class="p-5">
    <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
    </div>
    <form class="user">
        <div class="form-group">
            <input type="email" class="form-control form-control-user"
                id="exampleInputEmail" aria-describedby="emailHelp"
                placeholder="Enter Email Address...">
        </div>
        <div class="form-group">
            <input type="password" class="form-control form-control-user"
                id="exampleInputPassword" placeholder="Password">
        </div>
        <div class="form-group">
            <div class="custom-control custom-checkbox small">
                <input name="remember" id="id_remember" type="checkbox" class="custom-control-input">
                <label class="custom-control-label" for="id_remember">Remember
                    Me</label>
            </div>
        </div>
        <a href="{% url 'zuser:loginurl' %}" class="btn btn-primary btn-user btn-block">
            Login
        </a>
        <hr>
        <a href="index.html" class="btn btn-google btn-user btn-block">
            <i class="fab fa-google fa-fw"></i> Login with Google
        </a>
        <a href="index.html" class="btn btn-facebook btn-user btn-block">
            <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
        </a>
    </form>
    <hr>
    <div class="text-center">
        <a class="small" href="#">Forgot Password?</a>
    </div>
    <div class="text-center">
        <a class="small" href="{{ signup_url }}">Create an Account!</a>
    </div>
</div>
{% endblock %}